name: Build & Deploy Nuxt (Static) to GitHub Pages (root domain)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "nuxt-pages-deploy"
      cancel-in-progress: true

    # Expose secrets as env so podem usar env.<name> en les condicions if
    env:
      CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}
      CUSTOM_DOMAIN_URL: ${{ secrets.CUSTOM_DOMAIN_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Show node/npm versions (debug)
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Build - generate static site
        # Assignem NUXT_PUBLIC_SITE_URL amb un fallback a https://$CUSTOM_DOMAIN
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          NUXT_PUBLIC_SITE_URL: ${{ env.CUSTOM_DOMAIN_URL }}
          CUSTOM_DOMAIN: ${{ env.CUSTOM_DOMAIN }}
        run: |
          # fallback: si no hi ha CUSTOM_DOMAIN_URL, usem https://$CUSTOM_DOMAIN
          if [ -z "$NUXT_PUBLIC_SITE_URL" ] && [ -n "$CUSTOM_DOMAIN" ]; then
            export NUXT_PUBLIC_SITE_URL="https://$CUSTOM_DOMAIN"
            echo "Set NUXT_PUBLIC_SITE_URL to $NUXT_PUBLIC_SITE_URL"
          else
            echo "NUXT_PUBLIC_SITE_URL is $NUXT_PUBLIC_SITE_URL"
          fi

          # run generate
          npx nuxi generate --no-exit-on-error

      - name: Verify output
        run: |
          echo "Output folder size:"
          du -sh .output/public || true
          ls -la .output/public | sed -n '1,200p' || true

      - name: Create CNAME (custom domain)
        if: env.CUSTOM_DOMAIN != ''
        run: |
          echo "${{ env.CUSTOM_DOMAIN }}" > .output/public/CNAME
          echo "CNAME created for: ${{ env.CUSTOM_DOMAIN }}"

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .output/public

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1